<?php

namespace AppBundle\Repository;

/**
 * regles_competitionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class regles_competitionsRepository extends \Doctrine\ORM\EntityRepository
{
}
