AppBundle\Entity\Club:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ClubRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        libelle:
            type: string
            length: 255
        nbrJoueurs:
            type: integer
    lifecycleCallbacks: {  }
