AppBundle\Entity\Competition:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CompetitionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        libelle:
            type: string
            length: 255
    manyToOne:
        local:
          targetEntity: AppBundle\Entity\Local
          joinColumn:
            name: local
            referencedColumnName: id
    manyToMany:
        competition:
          targetEntity: AppBundle\Entity\Team
          joinTable:
            name: teams_competitions
            joinColumns:
              team_id:
                referencedColumnName: id
            inverseJoinColumns:
              competition_id:
                referencedColumnName: id
    lifecycleCallbacks: {  }
